version: '3'

services:
  web_application:
    build: ./applications/web_application
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./applications/web_application/tweets:/tweets
      - ./applications/web_application/FXES:/FXES
    ports:
      - "8000:8000"