# Generated by Django 5.0.3 on 2024-03-05 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 3, 5, 17, 25, 9, 643639), verbose_name='date published')),
                ('email_notified', models.BooleanField(default=False)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.user')),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.user')),
            ],
        ),
    ]
